### ISSUE TITLE
Destroy on resize issue

### ISSUE THREAD

**Issue by pixedd** [smashingboxes/OwlCarousel2#485]
When triggering destroy event on resize (only once), result is: TypeError: this.e is null for:

	/**
	 * Checks window `resize` event.
	 * @protected
	 */
	Owl.prototype.onThrottledResize = function() {
		window.clearTimeout(this.resizeTimer);
		this.resizeTimer = window.setTimeout(this.e._onResize, this.settings.responsiveRefreshRate);
	};

**Comment by bjawnie** [comment]
+1 same error

**Comment by dvera123** [comment]
any fix for this?

**Comment by dvera123** [comment]
I need to do more test here, but why this.e becomes null after destroy?

should not get their default values instead of null?

like these:

	e = {
		_onDragStart: null,
		_onDragMove: null,
		_onDragEnd: null,
		_transitionEnd: null,
		_resizer: null,
		_responsiveCall: null,
		_goToLoop: null,
		_checkVisibile: null
	};

**Comment by SuchyTheMaster** [comment]
I have exactly the same problem. :(

After destroying carousel by:
```javascript
$('#myCarousel').trigger('destroy.owl.carousel');
```

carousel is destroyed, but durring resize it's generate error

```javascript
Uncaught TypeError: Cannot read property '_onResize' of null
```

so all JS breaks down. :(

Even if this.e should give other values (not null), why don't wrap this this into try cath?
Maybe it will be temporrary solution to avoid breaking JS.

**Comment by PaskR** [comment]
Same problem after destroying carousel although I rebuilt it after...

**Comment by pixedd** [comment]
The js file in the repo is not the good one, you need to clone the repo and then rebuild it with Grunt.
This version should work fine : http://codepen.io/anon/pen/GJKBrR

**Comment by iamkeir** [comment]
I went digging in the code - looks like the responsive listener (specifically `_onResize`) is not being destroyed properly.

Tracked it down to line 622:
```this.resizeTimer = window.setTimeout(this.e._onResize, this.settings.responsiveRefreshRate);```

My JS is not great so I don't trust myself to fix it - but I thought I came up with a sneaky (and dirty) fix in the meantime: the error relates to a responsive carousel so I was going to reinit the carousel with `responsive: false` just before destroying it... however, I cannot find any function in OwlCarousel2 to reinitialise/change options of an existing Carousel.

Any ideas re 1) a fix or 2) a reinit function?

**Comment by iamkeir** [comment]
Or could you destroy within the responsive object?
```
responsive: {
  0 : { [[ all options here ]] },
  768 : { [[destroy here ]] }
}
```

**Comment by greg5green** [comment]
As far as I know, this is fixed in beta 3 (I think via 2064682).

Please upgrade to the newest version and if this issue still exists, we can reopen it.

**Comment by iamkeir** [comment]
Yep, can confirm that bug is no longer present in latest release - thanks @greg5green!

**Comment by vastra** [comment]
This is broken again in beta 2.4

When resizing the window:
`owl.carousel.js:622 Uncaught TypeError: Cannot read property '_onResize' of null`

**Comment by greg5green** [comment]
@vastra beta 3 is the most recent release that has this fixed

**Comment by julie44** [comment]
using beta3 for  _checkVisible error causes 'Uncaught TypeError: this.$backdrop.one(...).emulateTransitionEnd is not a function' in bootstrap js

**Comment by swannknani** [comment]
+1

**Comment by daviddeutsch** [comment]
@swannknani - do you mean this bug has resurfaced? The last answer from @greg5green was that it was fixed.

**Comment by jesspritchard** [comment]
Should this release have the fix? https://github.com/OwlCarousel2/OwlCarousel2/releases/tag/2.0.0-beta.3

I have used this version and although it fixes the resize issue, now my carousel is blank?

**Comment by angelarted** [comment]
Well, I'm sad to write this, but I'm using the latest version (2.0.0-beta.2.4) and this error still occurs..

**Comment by vastra** [comment]
I switched to slick.js, I've been writing more code to try and fix
owlcarousel than I would've writing my own plug-in. I would recommend
trying slick.js as it hasn't failed me yet, using 5 different
configurations on the same site (ecommerce, clients just love those
carousels)
