### ISSUE TITLE
Error when loop option used on slideshow with single item

### ISSUE THREAD

**Issue by ChrisHughes** [smashingboxes/OwlCarousel2#548]
Just noticed that there is a js error in the carousel's javascript when you run the slideshow with loop set to true and just one item in the carousel. Have tested and confirmed this in two browsers.
Backtrace is as follows
```
Uncaught TypeError: Cannot read property 'clone' of undefined 
Owl.Pipe.run               owl.carousel.js:299
proxy                      jquery-1.9.1.js:818
Owl.update                 owl.carousel.js:533
Owl.refresh                owl.carousel.js:579
Owl.initialize             owl.carousel.js:426
Owl                        owl.carousel.js:194
(anonymous function)       owl.carousel.js:1797
jQuery.extend.each         jquery-1.9.1.js:648
jQuery.fn.jQuery.each      jquery-1.9.1.js:270
$.fn.owlCarousel           owl.carousel.js:1795
```

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?

**Comment by ozergul** [comment]
Solution is simple:
```
$('.carousel').each(function(){
   if( $(this).find("div").length > 1 ) $(this).owlCarousel(options)
});
```

**Comment by greg5green** [comment]
This is fixed in the newest version of OwlCarousel2. You can grab it from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip or bower

**Comment by saizeci** [comment]
This issue is still present: "TypeError: items[clones[(clones.length - 1)]] is undefined
[Learn More]"
