### ISSUE TITLE
Dots nav not working normally in responsive mode

### ISSUE THREAD

**Issue by tacbephot** [smashingboxes/OwlCarousel2#707]
Hi there,
I found a issue, even in responsive example here http://www.owlcarousel.owlgraphic.com/demos/responsive.html, when you click on the third dot, it not active, it actived the second dot.

Please help

**Comment by philecker** [comment]
I've experienced this issue as well. I did notice that when displaying 1 "item" the pagination works correctly, but if there are 5 items displaying 2 items at a time that the last dot won't show active. Any help with this would be greatly appreciated.

**Comment by tacbephot** [comment]
i found best solution is use this :  https://github.com/metafizzy/flickity

**Comment by philecker** [comment]
That really an option for me, I need to figure out a solution to get this working.

**Comment by baubbelayponge** [comment]
I also have this issue.

**Comment by constantin-iliescu** [comment]
Same issue here.
I have 3 items and display only 2. The second dot is never active.

**Comment by davidangel** [comment]
I'm not seeing any dots...

```
jQuery(".home #video-tab .video-list").addClass('owl-carousel').owlCarousel({
            margin:20,
            stagePadding:30,
            pagination: true,
            navigation: true,
            responsive:{
                0:{
                    items:1
                },
                480:{
                    items:2
                },
                760:{
                    items:3
                }
            }
        });
```

**Comment by constantin-iliescu** [comment]
Th

**Comment by constantin-iliescu** [comment]
@davidangel: I think this code is for version 1. You shoul use dots:true instead of pagination:true.

**Comment by tsarma** [comment]
Dot issue is still there, any solution

**Comment by stevenw00** [comment]
I was having the same issue too. But it looks like the newest 2.0.0-beta.3 fixes this issue.

**Comment by greg5green** [comment]
Thanks for the input @stevenw00! After looking at this, I've confirmed that it is fixed in the newest version (https://github.com/smashingboxes/OwlCarousel2/releases/tag/2.0.0-beta.3 or on Bower)

**Comment by greg5green** [comment]
Btw, this was fixed via #231 if anyone is curious about the code used

**Comment by eatarandom** [comment]
I'm still having this issue in `2.0.0-beta.2.4`. It only appears at the breakpoint `768`. I'm testing with 3 items. My config is as follows: 
```
{
  items: 1,
  loop: false,
  mouseDrag: hasTouch,
  pullDrag: hasTouch,
  responsive:{
    768: {
      items: 2
    },
    1260: {
      items: 3,
      dots: false
    }
  }   
}
```
