### ISSUE TITLE
Center doesn't work perfectly when combined with RTL

### ISSUE THREAD

**Issue by mhyassin** [smashingboxes/OwlCarousel2#968]
The center item appears shifted to right by an item while using rtl:true.
To test just open: http://www.owlcarousel.owlgraphic.com/demos/rtl.html
Write this in the console: 
<code>
//destory intialized carousel
```javascript
$('.owl-carousel').trigger('destroy.owl.carousel');
```
//remove owl-stage-outer with keeping its children items
```javascript
$('.owl-carousel').append($('.owl-carousel .owl-stage-outer').children());
$('.owl-carousel .owl-stage-outer').remove();
```
//reintialize owl carousel with rtl and center both set to true
```javascript
var owl = $('.owl-carousel');
              owl.owlCarousel({
                rtl: true,
                center: true,
                margin: 10,
                nav: true,
                loop: true,
                responsive: {
                  0: {
                    items: 1
                  },
                  600: {
                    items: 3
                  },
                  1000: {
                    items: 5
                  }
                }
     });
```
</code>

Then just inspect the elements of the carousel you'll get that the "center" class is added to the right item.

**Comment by greg5green** [comment]
This is fixed in beta 3 as far as I can tell. You can grab it off bower or the website (http://smashingboxes.github.io/OwlCarousel2/)

**Comment by mhyassin** [comment]
Dear, It's not fixed even in the latest version, I'm testing it on http://www.owlcarousel.owlgraphic.com/demos/rtl.html which uses beta 3

**Comment by greg5green** [comment]
No dear. It does not.

**Comment by mhyassin** [comment]
Sorry I meant this link http://smashingboxes.github.io/OwlCarousel2/demos/rtl.html
<img width="721" alt="screen shot 2015-08-03 at 11 14 44 pm" src="https://cloud.githubusercontent.com/assets/2027112/9047875/1b2a173e-3a35-11e5-976a-af44329f7136.png">

**Comment by greg5green** [comment]
I see the issue now and have written a bug fix.

**Comment by mhyassin** [comment]
Thanks man :+1:

**Comment by muhamed87** [comment]
There are a problem when using **loop: false** with **rtl: true**,**center: true** at the last element, any one faced this before?

**Comment by sanj-sri88** [comment]
> There are a problem when using **loop: false** with **rtl: true**,**center: true** at the last element, any one faced this before?

@muhamed87 This issue is still there. I am using owl carousel latest version and if there is single image which I want to show inside of modal popup in center. Value of option is loop: false** with **rtl: true**,**center: true** then image is showing right hand side.

If anyone is having solution please suggest me 
FYI @greg5green , @joeyjoejoejr, @dennisreimann
